import { Playfair_Display, DM_Sans } from "next/font/google"
import "./globals.css"
import Header from "../components/Header";


const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-dm-sans",
});

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-playfair",
});

export const metadata = {
  title: "Job-App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className={`${dmSans.variable} ${playfairDisplay.variable} antialiased`}>
          {children}
        </main>
      </body>
    </html>
  );
}
